apiVersion: v1
kind: Service
metadata:
  name: custom-app-service
  namespace: custom-logging
spec:
  selector:
    app: custom-app
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
