apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: custom-app-envoy-metrics
  namespace: custom-logging
  labels:
    app: custom-app
spec:
  namespaceSelector:
    matchNames:
      - custom-logging
  selector:
    matchLabels:
      app: custom-app
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
